name: Gets List of file changes in current PR

on: [push]

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      files_changed: ${{ steps.changed_files.outputs.files_changed }}

    steps:
      # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Show output
        run: |
          echo '${{ toJSON(steps.changed-files-dir1.outputs) }}'

      - name: List all modified files
        run: |
          for file in ${{ steps.changed-files-dir1.outputs.modified_files }}; do
            echo "$file"
          done

      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "all=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)" >> "$GITHUB_ENV"
          echo "ts=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .ts$ | xargs)" >> "$GITHUB_ENV"

      - name: Get Changed Files
        uses: darmiel/changed-files@v1

      - name: Combine modified and added files
        run: cat .changed-files.{modified,added}.py | uniq > changed_file_list.txt
