name: Python unit testing

on: [pull_request]

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run Unit tests
        run: |
          cd unitTesting
          text="samplePythonfiles/"

          # Saves the PR's modified files name
          declare -a filesChanged
          filesChanged=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})

          # Need to send the list of all unit tests names in tests_list array
          declare -a tests_list
          tests_list=("samplePythonfiles/demo_1.py" "samplePythonfiles/demo_2.py")

          #Looping through the array and running the tests if match found.
          for key in "${!tests_list[@]}";
          do
            for value in "${!filesChanged[@]}";
            do
              echo "${filesChanged[$value]} $value"
              echo "${tests_list[$key]} $key"
              if [[ ${filesChanged[$value]} == ${tests_list[$key]} ]];
              then
                echo "inside if"
                test=${tests_list[$key]}
                test_name="${test#*$text}"
                echo ${test_name}
                #Runs unit tests
                python3 -m unittest ${test_name} -v
                break
              fi
            done
          done

#test_name="${tests_list[$key]} | cut -d'/' -f2" Not working
