name: Python unit testing

on: [push, pull_request]

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: List all the files changed in current PR
        run: |
          files_changed: ${{ git--no-pager diff --name-only --diff-filter=ACMRT ${{github.event.pull_request.base.sha}} ${{ github.event.pull_request.head.sha }} }}
          echo ${files_changed[@]}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: |
          cd unitTesting
          python3 -m unittest demo_1.py demo_2.py -v
