name: Python unit testing

on: [pull_request]

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run Unit tests
        run: |
          cd unitTesting

          #text="samplePythonfiles/"

          # Saves the PR's modified files name
          declare -a filesChanged
          filesChanged=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})

          # Need to send the list of all unit tests names in tests_list array
          declare -a tests_list
          tests_list=($(ls -F --file-type *.py))

          #Looping through the array and running the tests if match found.
          for key in "${!tests_list[@]}";
          do
            echo "tests_list: "${tests_list[$key]} "and index:" $key
            #list_value=${tests_list[$key]}
            #for value in "${!filesChanged[@]}";
            #do
              #if [[ ${filesChanged[$value]} =~ $list_value ]];
              if echo "${filesChanged[@]}" | grep -qw "${tests_list[$key]}";
              then
                #test=${tests_list[$key]}
                #test_name="${test#*$text}"
                test=${tests_list[$key]}
                #echo "Running unit test : ${test_name}"
                echo "Running unit test : ${test}"

                #Runs unit tests
                #python3 -m unittest ${test_name} -v
                python3 -m unittest ${test} -v
                #break
              else
                echo "No match found"
              fi
            #done
          done

#test_name="${tests_list[$key]} | cut -d'/' -f2" Not working
