name: Python unit testing

on: [pull_request]

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run Unit tests
        run: |
          declare -a filesChanged
          filesChanged=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})

          # echo "${filesChanged[@]}"

          check_file=" samplePythonfiles/demo_1.py "
          echo $check_file

          unit_test=$check_file | cut -d'/' -f2

          echo $unit_test

          # if $check_file in ${filesChanged[@]};
          if [[ $filesChanged[@] == *"$check_file"* ]];
          then
            cd unitTesting
            python3 -m unittest $unit_test -v
          else
            echo "No Unit tests to run"
          fi
