name: Python unit testing

on: [pull_request]

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run Unit tests
        run: |
          declare -a filesChanged
          filesChanged=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          # echo "${filesChanged[@]}"

          tests_list= ("samplePythonfiles/demo_1.py", "samplePythonfiles/demo_1.py")
          echo $tests_list

          for key in "${!tests_list[@]}";
          do
            echo $tests_list[$key]
            if [[ $filesChanged[@] == "$tests_list[$key]" ]];
            then
              cd unitTesting
              python3 -m unittest ($tests_list[1] | cut -d'/' -f2) -v
            else
              echo "No Unit tests to run"
            fi
          done
